### PR TITLE
chore: bump android-sdk-ui from 24.3.0 to 25.0.0

### PR DESCRIPTION
**Pull request by techouse**
## Summary

The recently released [Braze Android SDK v25](https://github.com/braze-inc/braze-android-sdk/blob/master/CHANGELOG.md#2500) is now hosted on Maven Central which means that

```groovy
repositories {
  maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
}
```

can now be removed from `build.gradle`.

Also, the dependency name has been renamed from

```groovy
 'com.appboy:android-sdk-ui'
```

to

```groovy
 'com.braze:android-sdk-ui'
```

 ## Testing Plan
- Ran test suite locally. All tests passed.
- Tested using a locally built artifact `android-appboy-kit-release.aar`. Works OK.

### CODE REVIEW

**Comment by techouse** [comment]
Can someone please take a look at this?

**Comment by einsteinx2** [comment]
Apologies for the delay on this. We'll need to do some testing to confirm there are no breaking changes since it's a major version bump, then we can merge this.

**Comment by techouse** [comment]
Thanks @einsteinx2 😄 

I don't believe that any breaking changes have been made in v25.0.0 https://www.braze.com/docs/developer_guide/platform_integration_guides/android/changelog/#2500

There however were breaking changes in v26.0.0 https://www.braze.com/docs/developer_guide/platform_integration_guides/android/changelog/#2600

**Review by markvdouw — COMMENTED** [review]
Approve

**Pull request merged**
